version: 0.2

phases:
    #install:
    #pre_build:
    build:
        commands:
            - docker login -u $dockerlogin -p $dockerpassword
            #- docker run --rm -v $(pwd)/SQL:/flyway/SQL -v $(pwd)/conf:/flyway/conf flyway/flyway -enterprise clean
            #- docker run --rm -v $(pwd)/SQL:/flyway/SQL -v $(pwd)/conf:/flyway/conf flyway/flyway -enterprise validate
            #- docker run --rm -v $(pwd)/SQL:/flyway/SQL -v $(pwd)/conf:/flyway/conf flyway/flyway -enterprise -dryRunOutput="/flyway/SQL/output.sql" migrate


            #- docker run --rm -v $(pwd)/SQL:/flyway/SQL -v $(pwd)/conf:/flyway/conf redgate/flyway flyway migrate
            #- docker run --rm -v $(pwd)/sql:/flyway/sql -v $(pwd)/conf:/flyway/conf flyway/flyway repair
            #- docker run --rm -v $(pwd)/sql:/flyway/sql -v $(pwd)/conf:/flyway/conf flyway/flyway migrate 
            - docker run --rm -v $(pwd)/sql:/flyway/sql -v $(pwd)/conf:/flyway/conf flyway/flyway clean 
    #post_build:



#        docker run --rm -v c:\Users\grant\Documents\HamShackRadio\SQL:/flyway/SQL -v c:\Users\grant\Documents\HamShackRadio\conf:/flyway/conf flyway/flyway -enterprise clean
#artifacts:
#    files:
#        $(pwd)/SQL/output.sql
