version: 0.2

phases:
    #install:
    #pre_build:
    build:
        commands:
            # Docker login to avoid getting throttled
            - docker login -u $dockerlogin -p $dockerpassword

            - docker run --rm -v $(pwd)/sql:/flyway/sql -v $(pwd)/conf:/flyway/conf flyway/flyway clean 
            #- docker run --rm -v $(pwd)/sql:/flyway/sql -v $(pwd)/conf:/flyway/conf flyway/flyway repair
            #- docker run --rm -v ./sql:/flyway/sql -v $(pwd)/conf:/flyway/conf flyway/flyway migrate 
            - docker run --rm -v $(pwd)/sql:/sql -v $(pwd)/conf:/flyway/conf flyway/flyway migrate 
    #post_build:
#artifacts:
#    files:
