version: 0.2

phases:
    #install:
    #pre_build:
    build:
        commands:
            # Docker login to avoid getting throttled
            - docker login -u $dockerlogin -p $dockerpassword

            #- docker run --rm -v $(pwd)/sql:/flyway/sql -v $(pwd)/conf:/flyway/conf flyway/flyway clean 
            #- docker run --rm -v $(pwd)/sql:/flyway/sql -v $(pwd)/conf:/flyway/conf flyway/flyway repair
            #- realpath ./sql 
            #- docker run --rm -v "$(pwd)/sql:/flyway/sql" -v "$(pwd)/conf:/flyway/conf" redgate/flyway migrate -X
            - docker run --rm -v "$(pwd)/dude:/flyway/sql" -v "$(pwd)/conf:/flyway/conf" redgate/flyway migrate -X
            #- docker run --rm -v $(pwd)/sql:/flyway/sql -v $(pwd)/conf:/flyway/conf redgate/flyway migrate
    #post_build:
#artifacts:
#    files:
