databaseType = "PostgreSql"
id = "a52d7faa-f6fb-40bc-8d91-e6583b015bc1"
name = "local"

[environments.development]
displayName = "Development database"
schemas = [ "radio", "public" ]
url = "jdbc:postgresql://localhost:5432/hamshackradio?user=postgres&password=*cthulhu1988"

[environments.FinancialTesting]
url = "jdbc:postgresql://localhost:5432/hsrft"
schemas = [ "radio", "public" ]

[flyway]
cleanDisabled = false
environment = "development"
licenseKey = "FL0171A9FD37E70C17E2F92D1A8E37235B8B0576E5FED16B5EF9833F269E4101412163495D2598C52C295DC79207108D12275771F350734FDB40AE2F0A105DAAC6C47BCEFBCEF7212869DA1DBB0C2DEB0E27B7E478CCB3ADC638ED381B3323E10E278734D0BEE23563CCD9F8A2B2C8A2F153F89F33C1D0C6C96735CFF51BC6B23DEC2EFF56AB5D3CA4DA8EE9E19AAA88BDC48E8D104919AA23494FBF28104EA6B958AA494ABDA68C1638FCAB47C9FD2027BDFE39ED8EFD96D4BA05BE6DA09968A341A1F6D39B9D69D3363E86FE4DD84FD477BA4CD4641192BEAD93F5934740267C3B28E34B0AA19D30B17F4F5FD4FC578D8D12F9C5998FBFBDD25E4ED7BAFC422F47"
locations = [ "filesystem:./sql" ]
mixed = false
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

  [flywayDesktop.generate]
  undoScripts = false

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

  [[redgateCompare.staticDataTables]]
  schema = "radio"
  table = "bands"

  [[redgateCompare.staticDataTables]]
  schema = "radio"
  table = "countries"
