-- Script generated by Redgate Compare v1.30.3.102
SET check_function_bodies = false;


CREATE TYPE radiorange AS RANGE (subtype = float8,
subtype_diff = float8mi);


ALTER TABLE radio.radios ADD COLUMN reception radiorange;

SET check_function_bodies = true;
